# -*- coding: utf-8 -*-
"""Daniel Cuellar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsolxqXPhdOJJoM9N0dqNiQpHZEAzfdT
"""

import pandas as pd

df = pd.read_csv('data.csv')
df

promedio_edad = df['Age'].mean()

valores_nulos_por_columna = df.isnull().sum()

genero_mas_repetido =df['Gender'].mode()

hombres = (df['Gender']==0).sum()
hombres

mujeres = (df['Gender']==1).sum()
mujeres

Sports = (df['Sports']==1).sum()
Sports

estudiantes_deportes_por_genero = df.groupby('Gender')['Sports'].sum()
print(estudiantes_deportes_por_genero)

hombres_que_practican_deportes = df[(df['Gender'] == 0) & (df['Sports'] == 1)]['Sports'].count()
mujeres_que_practican_deportes = df[(df['Gender'] == 1) & (df['Sports'] == 1)]['Sports'].count()

print(f"Hombres que practican deportes: {hombres_que_practican_deportes}")
print(f"Mujeres que practican deportes: {mujeres_que_practican_deportes}")

tutorias = (df['Tutoring']==1).sum()
tutorias

tiempo_estudio_maximo = df['StudyTimeWeekly'].max()
tiempo_estudio_minimo = df['StudyTimeWeekly'].min()

print(f"Tiempo de estudio máximo por semana: {tiempo_estudio_maximo}")
print(f"Tiempo de estudio mínimo por semana: {tiempo_estudio_minimo}")